---QUERY 1---
SELECT 
    C.NOMBRE AS NOMBRE_CLIENTE,
    C.DIRECCION,
    S.NOMBRE AS NOMBRE_SUCURSAL,
    S.CIUDAD
FROM CLIENTES C
JOIN SUMINISTROS SU ON C.CODIGO = SU.CODIGO_CLIENTE
JOIN SUCURSALES S ON SU.CODIGO_SUCURSAL = S.CODIGO
JOIN VINOS V ON SU.CODIGO_VINO = V.CODIGO
WHERE
(   C.comunidadAutonoma = 'Castilla-La Mancha'
    OR
    C.comunidadAutonoma = 'Andalucía')
AND V.MARCA = 'Tablas de Daimiel'
AND SU.FECHA < TO_DATE('01092023', 'DDMMYYYY')
AND SU.FECHA > TO_DATE('01012023', 'DDMMYYYY')

---QUERY 2---
SELECT
    VINOS.MARCA,
    VINOS.AÑO,
    SUM(SUMINISTROS.CANTIDAD) AS TOTAL_CANTIDAD
FROM
    VINOS
JOIN SUMINISTROS ON VINOS.CODIGO = SUMINISTROS.CODIGO_VINO
JOIN CLIENTES ON SUMINISTROS.CODIGO_CLIENTE = CLIENTES.CODIGO
JOIN PRODUCTOR ON VINOS.CODIGO_PRODUCTOR = 6 ------------ AÑADE AQUI EL NUMERO DEL PRODUCTOR
WHERE
    CLIENTES.comunidadAutonoma = 'Baleares'
OR  CLIENTES.comunidadAutonoma = 'Extremadura'
OR  CLIENTES.comunidadAutonoma = 'País Valenciano'
GROUP BY
    VINOS.MARCA, VINOS.AÑO


---QUERY 3---
SELECT 
    CLIENTES.NOMBRE, 
    CLIENTES.TIPO, 
    SUM(SUMINISTROS.CANTIDAD) AS TOTAL_WINE
FROM 
    CLIENTES 
JOIN 
    SUMINISTROS ON CLIENTES.CODIGO = SUMINISTROS.CODIGO_CLIENTE 
JOIN 
    VINOS ON SUMINISTROS.CODIGO_VINO = VINOS.CODIGO 
WHERE 
    (VINOS.DENOMINACIONDEORIGEN = 'Rioja' OR VINOS.DENOMINACIONDEORIGEN = 'Albariño') 
    AND SUMINISTROS.CODIGO_SUCURSAL = 6 --enter the desired sucursal. 6 and 12 will produce results
GROUP BY 
    CLIENTES.NOMBRE, 
    CLIENTES.TIPO
HAVING 
    SUM(SUMINISTROS.CANTIDAD) > 0;