

---QUERY 3---
SELECT 
    CLIENTES.NOMBRE, 
    CLIENTES.TIPO, 
    SUM(SUMINISTROS.CANTIDAD) AS TOTAL_WINE
FROM 
    CLIENTES 
JOIN 
    SUMINISTROS ON CLIENTES.CODIGO = SUMINISTROS.CODIGO_CLIENTE 
JOIN 
    VINOS ON SUMINISTROS.CODIGO_VINO = VINOS.CODIGO 
WHERE 
    (VINOS.DENOMINACIONDEORIGEN = 'Rioja' OR VINOS.DENOMINACIONDEORIGEN = 'Albariño') 
    AND SUMINISTROS.CODIGO_SUCURSAL = 6 --enter the desired sucursal. 6 and 12 will produce results
GROUP BY 
    CLIENTES.NOMBRE, 
    CLIENTES.TIPO
HAVING 
    SUM(SUMINISTROS.CANTIDAD) > 0;